node {
  step([$class: 'WsCleanup'])


  stage('Checkout aditional repo') {
    dir('CM') {
      git branch: 'master', url:"https://github.com/andresbelo12/ramp_up_cm.git"
    }
  }

  stage('Execute deployment with ansible') {
    dir('CM/ansible/frontend') {
      sh """
        ansible-playbook main.yml\
        -u ubuntu -vvv \
        -e ansible_ssh_private_key_file="~/Credentials/ramp-up-devops-andreslopezb-kp.pem"
        -e BACK_HOST=${BACK_HOST} \
      """
    }
  }

}